name: Test
on:
  pull_request:
  push:
    branches:
      - master
      - develop
jobs:
  tests:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Lint code
        run: pnpm lint
      - name: Format code
        run: pnpm format
      - name: Show uncommitted changes after linting and formatting
        run: git status
      - name: Show diff for pnpm-lock.yaml
        run: git diff --text pnpm-lock.yaml
      - name: Check if lint and format left uncommitted changes
        run: git diff --exit-code || true
      - name: Build
        run: pnpm build
      - name: Show uncommitted changes after build
        run: git status
      - name: Show diff for pnpm-lock.yaml after build
        run: git diff --text pnpm-lock.yaml
      - name: Check if build artifacts are committed
        run: git diff --exit-code || true
      - name: Run tests
        run: pnpm test
